const http=require('http'),crypto=require('crypto'),WebSocket=require('ws');
const PORT=process.env.PORT||3000;
const people=[["آدم","https://randomuser.me/api/portraits/men/11.jpg","رجل","نظارات","لحية"],["ليان","https://randomuser.me/api/portraits/women/12.jpg","امرأة","شعر طويل","نظارات"],["سامي","https://randomuser.me/api/portraits/men/22.jpg","رجل","لحية","شعر أسود"],["نور","https://randomuser.me/api/portraits/women/23.jpg","امرأة","شعر طويل","ابتسامة"],["مازن","https://randomuser.me/api/portraits/men/31.jpg","رجل","نظارات","شعر بني"],["جود","https://randomuser.me/api/portraits/women/31.jpg","امرأة","قبعة","شعر طويل"],["رامي","https://randomuser.me/api/portraits/men/41.jpg","رجل","شعر أسود","ابتسامة"],["سارة","https://randomuser.me/api/portraits/women/41.jpg","امرأة","شعر طويل","نظارات"],["كريم","https://randomuser.me/api/portraits/men/51.jpg","رجل","لحية","نظارات"],["ميرا","https://randomuser.me/api/portraits/women/51.jpg","امرأة","شعر بني","ابتسامة"],["حسن","https://randomuser.me/api/portraits/men/61.jpg","رجل","قبعة","لحية"],["ريم","https://randomuser.me/api/portraits/women/61.jpg","امرأة","شعر طويل","شعر أسود"],["عمر","https://randomuser.me/api/portraits/men/71.jpg","رجل","لحية","شعر بني"],["تالا","https://randomuser.me/api/portraits/women/71.jpg","امرأة","نظارات","شعر بني"],["فهد","https://randomuser.me/api/portraits/men/81.jpg","رجل","نظارات","لحية"],["دانا","https://randomuser.me/api/portraits/women/81.jpg","امرأة","قبعة","شعر طويل"]].map((x,i)=>({id:i,name:x[0],img:x[1],t:x.slice(2)}));
const questions=[["هل الشخصية رجل؟","رجل"],["هل الشخصية امرأة؟","امرأة"],["هل تلبس نظارات؟","نظارات"],["هل لديها لحية؟","لحية"],["هل تلبس قبعة؟","قبعة"],["هل شعرها طويل؟","شعر طويل"],["هل شعرها أسود؟","شعر أسود"],["هل شعرها بني؟","شعر بني"],["هل لديها ابتسامة؟","ابتسامة"]];
const rooms=new Map(),uid=()=>crypto.randomUUID(),newCode=()=>{let c;do c=Math.random().toString(36).slice(2,6).toUpperCase();while(rooms.has(c));return c};
const send=(s,o)=>s.readyState===1&&s.send(JSON.stringify(o));
function broadcast(r){const players=[...r.ps.values()].map(p=>({id:p.id,name:p.name,char:p.char}));for(const p of r.ps.values())send(p.ws,{type:'state',room:r.code,host:r.host,phase:r.phase,turn:r.turn,players});}
function leave(ws){for(const [c,r] of rooms){for(const [id,p] of r.ps){if(p.ws===ws){r.ps.delete(id);if(r.host===id)r.host=r.ps.keys().next().value;if(!r.ps.size)rooms.delete(c);else broadcast(r);return;}}}}
const page=()=>`<!doctype html><html lang="ar" dir="rtl"><meta name="viewport" content="width=device-width,initial-scale=1"><title>منو هو؟</title><style>*{box-sizing:border-box}body{margin:0;background:#070c16;color:#fff;font-family:system-ui,Tahoma}.wrap{max-width:1050px;margin:auto;padding:18px}.card{background:#101a2b;border:1px solid #ffffff14;border-radius:24px;padding:20px;margin-bottom:14px}.hero{text-align:center;padding:42px 20px}.title{font-size:42px;font-weight:900}.muted{color:#98a8bd}.input{width:100%;padding:13px;border-radius:13px;background:#08111f;border:1px solid #ffffff18;color:white;margin:6px 0}.btn{padding:13px 18px;border:0;border-radius:14px;font-weight:800;cursor:pointer}.primary{background:#42d9ff;color:#04101b}.secondary{background:#ffffff0d;color:white}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.person{background:#0b1524;border:2px solid transparent;border-radius:18px;padding:7px;text-align:center;cursor:pointer}.person img{width:100%;aspect-ratio:1;object-fit:cover;border-radius:13px}.person b{display:block;margin-top:5px}.person small{color:#94a5ba;font-size:10px}.selected{border-color:#42d9ff}.taken{opacity:.3}.players{display:flex;gap:8px;flex-wrap:wrap}.player{padding:8px 11px;background:#ffffff0b;border-radius:12px}.code{font-size:38px;letter-spacing:7px;color:#42d9ff}.q{text-align:center;font-size:21px;padding:18px}.qs{display:flex;gap:7px;flex-wrap:wrap;justify-content:center}.qbtn{padding:11px 14px;border-radius:12px;border:1px solid #ffffff18;background:#ffffff0a;color:#fff}@media(max-width:700px){.grid{grid-template-columns:repeat(3,1fr)}.title{font-size:32px}}</style><div class="wrap"><div class="card hero" id="home"><div class="title">منو هو؟</div><p class="muted">لعبة تخمين جماعية — كل لاعب يختار شخصية بشرية مختلفة.</p><input id="n" class="input" placeholder="اسمك"><button class="btn primary" onclick="create()">إنشاء غرفة</button><hr><input id="jn" class="input" placeholder="اسمك"><input id="rc" class="input" maxlength="4" placeholder="رمز الغرفة"><button class="btn secondary" onclick="join()">انضمام</button></div><div id="app"></div></div><script>
let ws,me,room,myChar=null;const P=${JSON.stringify(people)},Q=${JSON.stringify(questions)};
function connect(){ws=new WebSocket((location.protocol==='https:'?'wss://':'ws://')+location.host);ws.onmessage=e=>{let m=JSON.parse(e.data);if(m.type==='welcome')me=m.id;if(m.type==='error')alert(m.message);if(m.type==='answer')alert(m.q+'\\nالجواب: '+(m.yes?'نعم':'لا'));if(m.type==='state'){room=m;render()}}}connect();
const send=o=>ws.send(JSON.stringify(o));
function create(){if(!n.value.trim())return alert('اكتب اسمك');send({type:'create',name:n.value})}
function join(){if(!jn.value.trim()||rc.value.length!==4)return alert('أدخل الاسم والرمز');send({type:'join',name:jn.value,code:rc.value.toUpperCase()})}
function pick(i){if(room.players.some(x=>x.char===i&&x.id!==me))return alert('الشخصية محجوزة');myChar=i;send({type:'pick',char:i})}
function start(){send({type:'start'})} function ask(i){send({type:'ask',q:i})}
function render(){document.getElementById('home').style.display='none';const app=document.getElementById('app');const players=room.players.map(p=>'<div class="player">'+p.name+(p.id===me?' — أنت':'')+(p.char!=null?' ✓':' — لم يختر')+'</div>').join('');const cards=P.map(x=>'<div class="person '+(myChar===x.id?'selected ':'')+(room.players.some(p=>p.char===x.id&&p.id!==me)?'taken':'')+'" onclick="pick('+x.id+')"><img src="'+x.img+'"><b>'+x.name+'</b><small>'+x.t.join(' • ')+'</small></div>').join('');if(room.phase==='lobby'){app.innerHTML='<div class="card"><h2>الغرفة <span class="code">'+room.room+'</span></h2><p class="muted">أرسل الرمز لأصدقائك — من 2 إلى 8 لاعبين.</p><div class="players">'+players+'</div><h3>اختر شخصيتك</h3><div class="grid">'+cards+'</div><br>'+(room.host===me?'<button class="btn primary" onclick="start()">ابدأ اللعبة</button>':'<p class="muted">بانتظار المضيف...</p>')+'</div>'}else{const qs=room.turn===me?Q.map((x,i)=>'<button class="qbtn" onclick="ask('+i+')">'+x[0]+'</button>').join(''):'انتظر دور اللاعب الحالي';app.innerHTML='<div class="card"><h2>اللعبة بدأت</h2><div class="players">'+players+'</div><div class="q"><div>'+qs+'</div></div><div class="grid">'+cards+'</div></div>'}}
</script></html>`;
const server=http.createServer((req,res)=>{if(req.url==='/health'){res.writeHead(200);return res.end('ok')}res.writeHead(200,{'Content-Type':'text/html;charset=utf-8'});res.end(page())});
const wss=new WebSocket.Server({server});wss.on('connection',ws=>{ws.on('message',raw=>{let m;try{m=JSON.parse(raw)}catch{return}
if(m.type==='create'){const r={code:newCode(),host:uid(),phase:'lobby',turn:null,secret:null,ps:new Map};r.ps.set(r.host,{id:r.host,name:String(m.name||'لاعب').slice(0,18),char:null,ws});rooms.set(r.code,r);send(ws,{type:'welcome',id:r.host});broadcast(r)}
else if(m.type==='join'){const r=rooms.get(String(m.code||'').toUpperCase());if(!r)return send(ws,{type:'error',message:'الغرفة غير موجودة'});if(r.ps.size>=8)return send(ws,{type:'error',message:'الغرفة ممتلئة'});const p={id:uid(),name:String(m.name||'لاعب').slice(0,18),char:null,ws};r.ps.set(p.id,p);send(ws,{type:'welcome',id:p.id});broadcast(r)}
else for(const r of rooms.values())for(const p of r.ps.values())if(p.ws===ws){
if(m.type==='pick'&&r.phase==='lobby'){if(!people[m.char]||[...r.ps.values()].some(x=>x.id!==p.id&&x.char===m.char))return send(ws,{type:'error',message:'الشخصية غير متاحة'});p.char=m.char;broadcast(r)}
if(m.type==='start'&&p.id===r.host){if(r.ps.size<2)return send(ws,{type:'error',message:'تحتاج لاعبين على الأقل'});if([...r.ps.values()].some(x=>x.char===null))return send(ws,{type:'error',message:'كل لاعب لازم يختار شخصية'});r.phase='game';r.turn=r.host;r.secret=[...r.ps.values()][Math.floor(Math.random()*r.ps.size)].char;broadcast(r)}
if(m.type==='ask'&&r.phase==='game'&&r.turn===p.id){const q=questions[m.q];const yes=people[r.secret].t.includes(q[1]);for(const x of r.ps.values())send(x.ws,{type:'answer',q:q[0],yes});const ids=[...r.ps.keys()],i=ids.indexOf(p.id);r.turn=ids[(i+1)%ids.length];broadcast(r)}
}});
ws.on('close',()=>leave(ws))});
server.listen(PORT,'0.0.0.0',()=>console.log('Who Is It multiplayer on '+PORT));