const http=require("http");
const port=process.env.PORT||3000;

const html=String.raw`<!doctype html>
<html lang="ar" dir="rtl">
<head>
<meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<title>مين هو؟ — لعبة الشخصيات</title>
<style>
:root{--bg:#07111f;--panel:#101d31;--panel2:#142640;--text:#f5f8ff;--muted:#9fb0c8;--cyan:#45d7ff;--pink:#ff6fbb;--yellow:#ffd45a;--green:#58e39b;--danger:#ff6878}
*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 15% 0,#16345d 0,#07111f 38%,#050b15 100%);color:var(--text);font-family:system-ui,-apple-system,"Segoe UI",Tahoma,sans-serif;min-height:100vh}
button{font:inherit;border:0;cursor:pointer}#app{max-width:1100px;margin:auto;padding:18px 16px 40px}.top{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:18px}.brand{display:flex;align-items:center;gap:10px}.logo{width:48px;height:48px;border-radius:16px;background:linear-gradient(135deg,var(--cyan),#6d7cff);display:grid;place-items:center;font-size:25px;box-shadow:0 12px 35px #45d7ff22}.brand h1{font-size:20px;margin:0}.brand small{color:var(--muted)}.pill{background:#ffffff0d;border:1px solid #ffffff14;border-radius:999px;padding:9px 13px;color:#dce8fa}
.screen{display:none}.screen.active{display:block}.hero{display:grid;grid-template-columns:1.1fr .9fr;gap:18px;align-items:stretch}.card{background:linear-gradient(180deg,#12233bdf,#0d192be8);border:1px solid #ffffff12;border-radius:28px;box-shadow:0 22px 70px #0005;backdrop-filter:blur(12px)}.heroMain{padding:32px;min-height:470px;display:flex;flex-direction:column;justify-content:center}.eyebrow{color:var(--cyan);font-weight:800;letter-spacing:.5px}.hero h2{font-size:clamp(42px,7vw,78px);line-height:.95;margin:12px 0}.hero p{color:var(--muted);font-size:18px;line-height:1.7;max-width:650px}.actions{display:flex;flex-wrap:wrap;gap:10px;margin-top:18px}.btn{padding:14px 20px;border-radius:16px;font-weight:800;transition:.18s;box-shadow:0 8px 22px #0002}.btn:hover{transform:translateY(-2px)}.primary{background:linear-gradient(135deg,var(--cyan),#6d7cff);color:#06101c}.secondary{background:#ffffff10;color:var(--text);border:1px solid #ffffff16}.danger{background:#ff68781a;color:#ff9aa5;border:1px solid #ff687833}.mascot{min-height:470px;display:grid;place-items:center;padding:25px;position:relative;overflow:hidden}.mascot:before,.mascot:after{content:"";position:absolute;border-radius:50%;filter:blur(4px)}.mascot:before{width:230px;height:230px;background:#45d7ff20;top:-50px;right:-30px}.mascot:after{width:200px;height:200px;background:#ff6fbb1a;bottom:-50px;left:-30px}.face{width:230px;height:230px;border-radius:48% 52% 46% 54%;background:linear-gradient(145deg,#ffd96a,#ff9f52);position:relative;box-shadow:inset -18px -20px 0 #d8733840,0 30px 70px #0005;z-index:1}.eye{position:absolute;width:34px;height:44px;background:#17243b;border-radius:50%;top:74px}.eye.l{right:55px}.eye.r{left:55px}.mouth{position:absolute;width:78px;height:36px;border-bottom:7px solid #17243b;border-radius:0 0 60px 60px;bottom:55px;left:76px}.spark{position:absolute;font-size:30px;z-index:2}.s1{top:40px;right:20px}.s2{bottom:70px;left:25px}.how{margin-top:18px;padding:22px}.how h3{margin:0 0 10px}.steps{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.step{padding:14px;background:#ffffff08;border-radius:18px;color:var(--muted)}.step b{display:block;color:var(--text);margin-bottom:5px}
.gameHead{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:14px}.gameTitle h2{margin:0;font-size:27px}.gameTitle span{color:var(--muted);font-size:14px}.stats{display:flex;gap:8px;flex-wrap:wrap}.stat{background:#ffffff09;border:1px solid #ffffff12;padding:9px 12px;border-radius:14px}.stat b{color:var(--cyan)}.board{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.char{position:relative;min-height:150px;padding:10px;border-radius:22px;background:linear-gradient(180deg,#172b47,#102037);border:1px solid #ffffff12;transition:.2s;overflow:hidden}.char:hover{transform:translateY(-2px)}.char.elim{opacity:.28;filter:grayscale(.8);transform:scale(.97)}.avatar{height:92px;border-radius:17px;display:grid;place-items:center;font-size:42px;margin-bottom:8px}.charName{font-weight:850}.traits{font-size:11px;color:var(--muted);margin-top:3px}.x{display:none;position:absolute;inset:0;place-items:center;font-size:58px;color:#ff6575;background:#07111f66}.elim .x{display:grid}.bottomBar{position:sticky;bottom:12px;margin-top:14px;display:flex;justify-content:center;gap:9px;flex-wrap:wrap}.hintPanel{padding:22px}.hintCard{padding:26px;border-radius:24px;background:linear-gradient(135deg,#172f4e,#101d31);border:1px solid #ffffff14;text-align:center}.hintIcon{font-size:46px}.hintCard h3{font-size:25px;margin:8px 0}.hintCard p{color:var(--muted);margin:0}.choices{display:flex;justify-content:center;gap:10px;margin-top:20px;flex-wrap:wrap}.choice{min-width:130px}.progress{height:7px;background:#ffffff0c;border-radius:9px;overflow:hidden;margin:14px 0}.progress i{display:block;height:100%;background:linear-gradient(90deg,var(--cyan),var(--pink));width:0;transition:.3s}.reveal{text-align:center;padding:38px}.reveal .avatar{width:150px;height:150px;margin:15px auto;font-size:70px}.score{font-size:40px;font-weight:900;color:var(--yellow)}.toast{position:fixed;left:50%;bottom:24px;transform:translateX(-50%) translateY(20px);opacity:0;background:#0d1b2e;border:1px solid #ffffff18;padding:12px 18px;border-radius:999px;transition:.25s;z-index:20}.toast.show{opacity:1;transform:translateX(-50%) translateY(0)}
@media(max-width:760px){#app{padding:12px 10px 30px}.hero{grid-template-columns:1fr}.mascot{min-height:270px}.heroMain{min-height:auto;padding:24px}.hero h2{font-size:54px}.steps{grid-template-columns:1fr}.board{gap:7px}.char{min-height:132px;padding:7px;border-radius:17px}.avatar{height:72px;font-size:34px}.traits{font-size:9px}.gameHead{align-items:flex-start;flex-direction:column}.stats{width:100%}}
</style></head>
<body><div id="app">
<div class="top"><div class="brand"><div class="logo">?</div><div><h1>مين هو؟</h1><small>لعبة كشف الشخصية</small></div></div><div class="pill" id="scorePill">النقاط: 0</div></div>

<section id="home" class="screen active">
<div class="hero"><div class="card heroMain"><div class="eyebrow">لعبة تخمين سريعة وممتعة</div><h2>مين هو؟</h2><p>اختار التلميحات، استبعد الشخصيات، وخمّن الشخصية السرية قبل الجميع.</p><div class="actions"><button class="btn primary" onclick="startGame()">ابدأ لعبة جديدة</button><button class="btn secondary" onclick="showHow()">طريقة اللعب</button></div></div>
<div class="card mascot"><span class="spark s1">✦</span><span class="spark s2">★</span><div class="face"><div class="eye l"></div><div class="eye r"></div><div class="mouth"></div></div></div></div>
<div class="card how" id="how"><h3>طريقة اللعب</h3><div class="steps"><div class="step"><b>1. ابدأ</b>يتم اختيار شخصية سرية عشوائياً.</div><div class="step"><b>2. اسأل</b>استخدم التلميحات لمعرفة صفاتها.</div><div class="step"><b>3. استبعد</b>اضغط على الشخصيات غير المناسبة ثم اكشف السر.</div></div></div>
</section>

<section id="boardScreen" class="screen"><div class="gameHead"><div class="gameTitle"><h2>لوحة الشخصيات</h2><span>اضغط على شخصية لاستبعادها يدوياً</span></div><div class="stats"><div class="stat">المتبقي <b id="remain">16</b></div><div class="stat">الجولة <b id="round">1</b></div></div></div><div class="card" style="padding:10px"><div class="board" id="board"></div></div><div class="bottomBar"><button class="btn primary" onclick="openHint()">💡 تلميح</button><button class="btn secondary" onclick="reveal()">🔍 كشف الشخصية</button><button class="btn danger" onclick="goHome()">خروج</button></div></section>

<section id="hintScreen" class="screen"><div class="gameHead"><div class="gameTitle"><h2>شاشة التلميحات</h2><span>كل إجابة مبنية على الشخصية السرية</span></div></div><div class="card hintPanel"><div class="progress"><i id="prog"></i></div><div class="hintCard"><div class="hintIcon">🕵️</div><h3 id="question">هل الشخصية تلبس نظارات؟</h3><p id="hintMeta">أجب بنعم أو لا، وسنساعدك على تضييق الاحتمالات.</p><div class="choices"><button class="btn primary choice" onclick="answer(true)">نعم</button><button class="btn secondary choice" onclick="answer(false)">لا</button></div></div></div><div class="bottomBar"><button class="btn secondary" onclick="backBoard()">العودة للوحة</button></div></section>

<section id="revealScreen" class="screen"><div class="card reveal"><div class="eyebrow">تم الكشف!</div><h2>الشخصية السرية هي</h2><div id="revealAvatar" class="avatar"></div><h3 id="revealName" style="font-size:30px;margin:8px"></h3><p id="revealTraits" style="color:var(--muted)"></p><div class="score" id="finalScore">+0</div><p style="color:var(--muted)">نقاط الجولة</p><div class="actions" style="justify-content:center"><button class="btn primary" onclick="startGame()">لعبة جديدة</button><button class="btn secondary" onclick="goHome()">الرئيسية</button></div></div></section>
</div><div id="toast" class="toast"></div>
<script>
const chars=[
{name:"آدم",emoji:"🧢",color:"#3aa9ff",traits:["قبعة","شاب","أزرق"]},{name:"ليان",emoji:"👓",color:"#ff78c8",traits:["نظارات","شعر طويل","وردي"]},{name:"سامي",emoji:"🧔",color:"#a67cff",traits:["لحية","شاب","بنفسجي"]},{name:"نور",emoji:"🎀",color:"#ff7b8e",traits:["شعر طويل","فيونكة","وردي"]},
{name:"مازن",emoji:"🕶️",color:"#42d6b3",traits:["نظارات شمسية","شاب","أخضر"]},{name:"جود",emoji:"👒",color:"#ffc857",traits:["قبعة","شعر طويل","أصفر"]},{name:"رامي",emoji:"🧑‍🚀",color:"#5b8cff",traits:["قبعة","شاب","أزرق"]},{name:"سارة",emoji:"🧣",color:"#ff9d52",traits:["وشاح","شعر طويل","برتقالي"]},
{name:"كريم",emoji:"🤓",color:"#63d5ff",traits:["نظارات","شاب","أزرق"]},{name:"ميرا",emoji:"🧑‍🎤",color:"#d56cff",traits:["شعر طويل","شاب","بنفسجي"]},{name:"حسن",emoji:"🧢",color:"#58e39b",traits:["قبعة","لحية","أخضر"]},{name:"ريم",emoji:"🎀",color:"#ff6fbb",traits:["فيونكة","شعر طويل","وردي"]},
{name:"عمر",emoji:"🧔",color:"#f0a85a",traits:["لحية","شاب","برتقالي"]},{name:"تالا",emoji:"👓",color:"#8d7cff",traits:["نظارات","شعر طويل","بنفسجي"]},{name:"فهد",emoji:"🕶️",color:"#4dd7d0",traits:["نظارات شمسية","لحية","أخضر"]},{name:"دانا",emoji:"🧣",color:"#ff668e",traits:["وشاح","شعر طويل","وردي"]}
];
const clues=[
["هل الشخصية تلبس نظارات؟","نظارات"],["هل الشخصية تلبس قبعة؟","قبعة"],["هل لدى الشخصية لحية؟","لحية"],["هل الشخصية لديها شعر طويل؟","شعر طويل"],["هل الشخصية تلبس وشاحاً؟","وشاح"],["هل الشخصية تلبس نظارات شمسية؟","نظارات شمسية"],["هل الشخصية لديها فيونكة؟","فيونكة"]
];
let secret=null, eliminated=new Set(), clueIndex=0, score=0, round=0;
function show(id){document.querySelectorAll(".screen").forEach(x=>x.classList.remove("active"));document.getElementById(id).classList.add("active");scrollTo(0,0)}
function startGame(){secret=chars[Math.floor(Math.random()*chars.length)];eliminated=new Set();clueIndex=0;round++;renderBoard();document.getElementById("round").textContent=round;show("boardScreen");toast("بدأت جولة جديدة! الشخصية السرية مخفية 🤫")}
function renderBoard(){const b=document.getElementById("board");b.innerHTML=chars.map((c,i)=>{const e=eliminated.has(i);return '<button class="char '+(e?"elim":"")+'" onclick="toggleElim('+i+')"><div class="avatar" style="background:'+c.color+'22">'+c.emoji+'</div><div class="charName">'+c.name+'</div><div class="traits">'+c.traits.join(" • ")+'</div><div class="x">✕</div></button>'}).join("");document.getElementById("remain").textContent=chars.length-eliminated.size}
function toggleElim(i){if(eliminated.has(i)) eliminated.delete(i); else eliminated.add(i);renderBoard()}
function openHint(){if(!secret)return;show("hintScreen");setHint()}
function setHint(){const c=clues[clueIndex%clues.length];document.getElementById("question").textContent=c[0];document.getElementById("prog").style.width=((clueIndex%clues.length+1)/clues.length*100)+"%"}
function answer(v){const trait=clues[clueIndex%clues.length][1], yes=secret.traits.includes(trait);toast(v===yes?"إجابة صحيحة للشخصية السرية":"الإجابة لا تطابق الشخصية السرية");clueIndex++;setTimeout(()=>{show("boardScreen");applyAutoElimination(trait,yes)},450)}
function applyAutoElimination(trait,yes){chars.forEach((c,i)=>{if(c.traits.includes(trait)!==yes) eliminated.add(i)});renderBoard()}
function backBoard(){show("boardScreen")}
function reveal(){if(!secret)return;const kept=chars.map((c,i)=>!eliminated.has(i)?i:null).filter(x=>x!==null);score+=kept.length===1&&chars[kept[0]]===secret?100:Math.max(10,100-kept.length*5);document.getElementById("scorePill").textContent="النقاط: "+score;document.getElementById("revealAvatar").textContent=secret.emoji;document.getElementById("revealAvatar").style.background=secret.color+"22";document.getElementById("revealName").textContent=secret.name;document.getElementById("revealTraits").textContent=secret.traits.join(" • ");document.getElementById("finalScore").textContent="+"+(kept.length===1&&chars[kept[0]]===secret?100:Math.max(10,100-kept.length*5));show("revealScreen")}
function goHome(){show("home")}
function showHow(){document.getElementById("how").scrollIntoView({behavior:"smooth"})}
function toast(t){const x=document.getElementById("toast");x.textContent=t;x.classList.add("show");setTimeout(()=>x.classList.remove("show"),1800)}
renderBoard();
</script></body></html>`;
http.createServer((req,res)=>{res.writeHead(200,{"Content-Type":"text/html; charset=utf-8","Cache-Control":"no-store"});res.end(html)}).listen(port,"0.0.0.0",()=>console.log("Who Is It running on "+port));