import http from "node:http";
import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import {fileURLToPath} from "node:url";
const __dirname=path.dirname(fileURLToPath(import.meta.url)), publicDir=path.join(__dirname,"public"), PORT=process.env.PORT||3000, TURN_MS=45000, rooms=new Map();
const WORDS=["كتاب","تفاح","موزة","سمكة","وردة","شجرة","نحلة","حصان","صورة","بابا","لبنة","نجمة","غيمة","كرسي","سيارة","طائرة","حديقة","فراشة","بستان","مدرسة","معلمة","حقيبة","نافذة","مكتبة","مطرقة","سفينة"];
const norm=w=>w.normalize("NFKC").replace(/[ًٌٍَُِّْـ]/g,"").replace(/[أإآ]/g,"ا").replace(/ى/g,"ي");
const letters=w=>[...norm(w)];
const shuffle=a=>{a=[...a];for(let i=a.length-1;i>0;i--){let j=crypto.randomInt(i+1);[a[i],a[j]]=[a[j],a[i]]}return a};
const code=()=>crypto.randomBytes(3).toString("hex").toUpperCase(), id=()=>crypto.randomUUID();
function chooseWords(n){let len=4;if(Math.random()<.35)len=5;let p=shuffle(WORDS.filter(w=>letters(w).length===len));if(p.length<n)p=shuffle(WORDS.filter(w=>letters(w).length===4));return p.slice(0,n)}
function match(hand,target){return hand.map(norm).sort().join("")===letters(target).sort().join("")}
function auto(room){if(room.phase!=="playing"||Date.now()<room.ends||room.winner)return;let p=room.players[room.turn];if(p.pending){p.hand.push(p.pending);p.pending=null}if(!p.hand.length)return;let c=p.hand.splice(crypto.randomInt(p.hand.length),1)[0],next=room.players[(room.turn+1)%room.players.length];next.pending=c;room.turn=(room.turn+1)%room.players.length;room.ends=Date.now()+TURN_MS}
function state(room,pid){let me=room.players.find(p=>p.id===pid);return {ok:true,room:room.code,phase:room.phase,turn:room.turn,ends:room.ends,winner:room.winner,me:me&&{id:me.id,name:me.name,target:me.target,hand:me.hand,pending:me.pending},players:room.players.map(p=>({id:p.id,name:p.name,handCount:p.hand.length+(p.pending?1:0)}))}}
function send(res,s,d){res.writeHead(s,{"content-type":"application/json; charset=utf-8","cache-control":"no-store"});res.end(JSON.stringify(d))}
async function body(req){return await new Promise((ok,bad)=>{let d="";req.on("data",c=>d+=c);req.on("end",()=>{try{ok(d?JSON.parse(d):{})}catch(e){bad(e)}})})}
function start(room){let ws=chooseWords(room.players.length),deck=shuffle(ws.flatMap(letters));room.players.forEach((p,i)=>{p.target=ws[i];p.hand=[];p.pending=null});deck.forEach((c,i)=>room.players[i%room.players.length].hand.push(c));let out=room.players.map(p=>p.hand.splice(crypto.randomInt(p.hand.length),1)[0]);room.players.forEach((p,i)=>p.pending=out[(i-1+room.players.length)%room.players.length]);room.phase="playing";room.turn=0;room.winner=null;room.ends=Date.now()+TURN_MS}
const server=http.createServer(async(req,res)=>{try{let u=new URL(req.url,"http://x");
if(req.method==="GET"&&u.pathname==="/health")return send(res,200,{ok:true,game:"harfha"});
if(req.method==="GET"&&u.pathname==="/api/state"){let r=rooms.get(u.searchParams.get("room")),p=u.searchParams.get("player");if(!r||!r.players.some(x=>x.id===p))return send(res,404,{error:"الغرفة غير موجودة"});auto(r);return send(res,200,state(r,p))}
if(req.method==="POST"){let b=await body(req);
if(u.pathname==="/api/create"){let r={code:code(),phase:"lobby",players:[],turn:0,ends:0,winner:null},p={id:id(),name:String(b.name||"لاعب").slice(0,20),target:null,hand:[],pending:null};r.players.push(p);rooms.set(r.code,r);return send(res,200,{room:r.code,player:p.id})}
if(u.pathname==="/api/join"){let r=rooms.get(String(b.room||"").toUpperCase());if(!r)return send(res,404,{error:"رمز الغرفة غير صحيح"});if(r.phase!=="lobby")return send(res,400,{error:"اللعبة بدأت"});if(r.players.length>=6)return send(res,400,{error:"الغرفة ممتلئة"});let p={id:id(),name:String(b.name||"لاعب").slice(0,20),target:null,hand:[],pending:null};r.players.push(p);return send(res,200,{room:r.code,player:p.id})}
if(u.pathname==="/api/start"){let r=rooms.get(String(b.room||"").toUpperCase());if(!r)return send(res,404,{error:"الغرفة غير موجودة"});if(r.players[0].id!==b.player)return send(res,403,{error:"المضيف فقط"});if(![2,4,6].includes(r.players.length))return send(res,400,{error:"اللعبة تحتاج 2 أو 4 أو 6 لاعبين"});start(r);return send(res,200,{ok:true})}
if(u.pathname==="/api/pass"){let r=rooms.get(String(b.room||"").toUpperCase());if(!r)return send(res,404,{error:"الغرفة غير موجودة"});auto(r);if(r.phase!=="playing")return send(res,400,{error:"الجولة انتهت"});if(r.players[r.turn].id!==b.player)return send(res,403,{error:"ليس دورك"});let p=r.players[r.turn];if(p.pending){p.hand.push(p.pending);p.pending=null}let i=Number(b.index);if(!Number.isInteger(i)||i<0||i>=p.hand.length)return send(res,400,{error:"حرف غير صالح"});let c=p.hand.splice(i,1)[0],next=r.players[(r.turn+1)%r.players.length];next.pending=c;if(match(p.hand,p.target)){r.winner=p.id;r.phase="finished"}else{r.turn=(r.turn+1)%r.players.length;r.ends=Date.now()+TURN_MS}return send(res,200,{ok:true})}}
let file=u.pathname==="/" ? "/index.html" : u.pathname;if(file.includes(".."))return send(res,400,{error:"bad path"});fs.readFile(path.join(publicDir,file),(e,d)=>{if(e)return send(res,404,{error:"not found"});let ext=path.extname(file),ct=ext===".html"?"text/html; charset=utf-8":ext===".css"?"text/css":"text/javascript; charset=utf-8";res.writeHead(200,{"content-type":ct});res.end(d)})}catch(e){send(res,500,{error:e.message})}});
server.listen(PORT,()=>console.log("Harfha on "+PORT));